# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 05:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180104_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 5, 23, 8, 230416, tzinfo=utc)),
        ),
    ]
